# API Laravel no Railway — só PHP (front Vue fica na Vercel).
# package.json/yarn.lock no Laravel ainda fazem o Nixpacks puxar Node/Yarn;
# isso colide LICENSE (yarn vs composer). Prioridade do composer resolve.

providers = ["php"]

[phases.setup]
nixPkgs = [
  "...",
  # https://nixos.org/manual/nixpkgs/stable/#var-meta-priority
  '(lib.recursiveUpdate php82Packages.composer { meta.priority = (php82Packages.composer.meta.priority or 0) - 1; })',
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs",
]

[phases.build]
cmds = []

[start]
cmd = "php artisan marag:doctor --fix && php artisan serve --host=0.0.0.0 --port=$PORT"
